// packages/cli/templates/vue/documents/welcome/pages/Close/ClosePage.vue
<template>
	<section class='page hero-page'>
		<p class='kicker'>Where to go next</p>
		<h2 class='hero-title'>Now, go build something.</h2>
		<p class='lead'>
			You've only scratched the surface. There's plenty more to explore, and it's all in the docs at
			<a href='https://format.dev/docs'>format.dev/docs</a>. If you get stuck, <a href='https://format.dev/contact'>reach out</a>
			and we'll help.
		</p>
	</section>
</template>

// packages/cli/templates/react/documents/welcome/pages/Close/ClosePage.tsx
export function ClosePage() {
	return (
		<section className='page hero-page'>
			<p className='kicker'>Where to go next</p>
			<h2 className='hero-title'>Now, go build something.</h2>
			<p className='lead'>
				You've only scratched the surface. There's plenty more to explore, and it's all in the docs at{' '}
				<a href='https://format.dev/docs'>format.dev/docs</a>. If you get stuck, <a href='https://format.dev/contact'>reach out</a>{' '}
				and we'll help.
			</p>
		</section>
	)
}
